name: MysqlInventoryBridge
main: net.craftersland.bridge.inventory.Inv
version: 2.4.1-MyMetaverseEdited-1.0.0
authors:
  - CraftersLand
  - RicardormDev
website: www.craftersland.net & mymetaverse.io
load: STARTUP
api-version: 1.16
description: Sync players inventorys over many servers using MySQL. This is an edited version for and by MyMetaverse
softdepend: [ProtocolLib]